### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by lencioni**
This file allows this package to be installed using Bower. I have
registered the package as `jquery-popupwindow` in the Bower package
registry. It can now be installed by executing:

  bower install jquery-popupwindow

More information on Bower can be found at:

  https://github.com/bower/bower
  http://bower.io

### CODE REVIEW

**Comment by hadees** [comment]
@lencioni you need to up the version number otherwise it won't update in bower

**Comment by lencioni** [comment]
@hadees I believe this would require a tag to be added to this repo, which I think only the owner or collaborators here are able to do. @mkdynamic, would you bump the version in bower.json and add a new release? I haven't been following the development of this project very closely, but it looks like 1.0.1 might make sense.

**Comment by mkdynamic** [comment]
@lencioni Thanks so much for this. I added you as a collaborator, if you want to bump the version/whatever please go for it! I'll try and scope but might be a few days before I get to it.

**Comment by lencioni** [comment]
v1.0.1 has been released.

**Pull request merged**
