### PR TITLE
Added ability to center popup on opener window...

### PR DESCRIPTION
**Pull request by jblashill**
A small feature I needed... thought I'd check if you also thought it might be useful...

### CODE REVIEW

**Comment by mkdynamic** [comment]
I like this idea, but wonder if the API can be simpler. What if you just keep `center` argument, but pass different options to determine how it functioned. `true` would center to screen (for backwards compat), `parent` would center relative to parent, `false` would not center?

**Comment by jblashill** [comment]
Hmmm.. I guess it's pretty subjective but I'm not a fan of having properties that swap between types (boolean / string)

How about this: keep 'center' as is and add a 'centerOn' attribute that can be an element or jquery selector? 'centerOn' would default to the window.

**Comment by jblashill** [comment]
Sorry, I meant to say that 'centerOn' would default to the screen to maintain backwards compatibility...

**Comment by lencioni** [comment]
@jblashill I agree with your assessment about not having properties swap between types. What do you think about `centerContext` which would take an object and have a default value of `screen`?

**Comment by jblashill** [comment]
@lencioni Makes sense to me!

**Comment by lencioni** [comment]
Actually, now that I think about it a little more, `center` could be `screen` by default. To turn off auto-centering, you could set it to `null`, or to center on a different object, just use that object instead of `screen`.

**Comment by thorst** [comment]
I was just going to note that this doesn't work for multiple monitors. But it looks like you are working on it. Looking forward to the fix.

**Comment by lencioni** [comment]
Closing in favor of #9. Thanks for the pull request!

**Pull request closed without merging**
